name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Wait for Mongo and Redis
        run: |
          echo "Waiting for Mongo on localhost:27017..."
          for i in {1..30}; do
            if bash -c "</dev/tcp/localhost/27017" >/dev/null 2>&1; then echo "Mongo is up"; break; fi
            sleep 1
          done
          echo "Waiting for Redis on localhost:6379..."
          for i in {1..30}; do
            if bash -c "</dev/tcp/localhost/6379" >/dev/null 2>&1; then echo "Redis is up"; break; fi
            sleep 1
          done

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        env:
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_DB_NAME: ci_test_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          NODE_ENV: test
        run: npm test -- --runInBand --detectOpenHandles

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/node-redis-mongo:latest
            ${{ secrets.DOCKER_USERNAME }}/node-redis-mongo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
